apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.image.label }}-secret
  namespace: {{ .Values.image.namespace }}
data:
  POSTGRES_USER: Y2FzdF9kYl91c2VybmFtZQ==
  POSTGRES_PASSWORD: Y2FzdF9kYl9wYXNzd29yZA==
  POSTGRES_DB: Y2FzdF9kYl9kZXY=