apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: movie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CAST_SERVICE_HOST_URL
              value: {{ .Values.env.CAST_SERVICE_HOST_URL }}
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.service.name }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.service.name }}-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.service.name }}-config
                  key: POSTGRES_DB
          ports:
            - name: movie-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP
