apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.label }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.label }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CAST_SERVICE_HOST_URL
              value: {{ .Values.env.CAST_SERVICE_HOST_URL }}
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.image.label }}-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.image.label }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.image.label }}-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: movie-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP
