apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.label }}
spec:
  selector:
    app: {{ .Values.service.label }}
  ports:
  - name: movie-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }} 