apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.image.name }}-statefulset
  namespace: {{ .Values.image.namespace }}
  labels:
    app: castdb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: castdb
  template:
    metadata:
      labels:
        app: castdb
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: 'postgres:14'
          ports:
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: cast_db_username
            - name: POSTGRES_PASSWORD
              value: cast_db_password
            - name: POSTGRES_DB
              value: cast_db_dev
          volumeMounts:
            - mountPath: /var/lib/postgresql/data1
              name: postgres-pv-claim
      volumes:
      - name: postgres-pv-claim
        persistentVolumeClaim:
          claimName: postgres-pv-claim
