apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.image.repository }}
  name: postgres-pv-claim-{{ .Values.image.namespace }}
  namespace: {{ .Values.image.namespace }}
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi