apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-{{ .Values.image.namespace }}
  namespace: {{ .Values.image.namespace }}
  labels:
    type: local
    app: {{ .Values.image.repository }}
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"