apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-service
  namespace: {{ .Values.image.namespace }}
  labels:
    app: castdb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: castdb-port
  selector:
    app: castdb