apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.image.name }}-statefulset
  namespace: {{ .Values.image.namespace }}
  labels:
    app: {{ .Values.image.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name:  {{ .Values.image.label }}
          image: postgres
          ports:
            - name: {{ .Values.service.name }}
              containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: moviedb-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Values.service.name }}-volume-1
      volumes:
        - emptyDir: {}
          name: {{ .Values.service.name }}-volume-1