apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.image.name }}-statefulset
  namespace: {{ .Values.image.namespace }}
  labels:
    app: {{ .Values.image.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "Always"
          ports:
            - name: {{ .Values.service.name }}
              containerPort: 5432
              protocol: TCP
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Values.image.label }}-secret
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.image.label }}-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.image.label }}-secret
                key: POSTGRES_PASSWORD 
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust                
          volumeMounts:   
            - name: postgresdata2                # name of the Volume
              mountPath: /var/lib/postgresql/data   # path inside the container
      volumes:
      - name: postgresdata2
        persistentVolumeClaim:
          claimName: postgres-pv-claim2-{{ .Values.image.namespace }}

