apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.image.name }}-statefulset
  namespace: {{ .Values.image.namespace }}
  labels:
    app: {{ .Values.image.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.label }}
    spec:
      containers:
        - name:     {{ .Values.image.label }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          envFrom:
            - secretRef:
                name: moviedb-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Values.service.name }}-volume-1
      volumes:
        - emptyDir: {}
          name: {{ .Values.service.name }}-volume-1