apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv2
  namespace: {{ .Values.image.namespace }}
  labels:
    type: local
    app: {{ .Values.image.name }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"