apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: moviedb
  name: postgres-pv-claim
  namespace: {{ .Values.image.namespace }}
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300M