apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-service
  namespace: {{ .Values.image.namespace }}
  labels:
    app: {{ .Values.image.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: {{ .Values.image.label }}-port
  selector:
    app: {{ .Values.image.name }}