replicaCount: 1

image:
  repository: ""
  pullPolicy: "Always"
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer 
  port: ""
  targetPort: 8001
  name: "cast_service"
  host: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  port: 81
  hosts:
    - host: fastapi-gateway.prod
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}

namespace: staging 

env:          
 SERVER_PORT: 8001