apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: movie-secret
  namespace: prod
data:
  POSTGRES_USER: bW92aWVfZGJfdXNlcm5hbWU=
  POSTGRES_PASSWORD: bW92aWVfZGJfcGFzc3dvcmQ=
  POSTGRES_DB: bW92aWVfZGJfZGV2