apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: cast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast
  template:
    metadata:
      labels:
        app: cast
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
            - name: POSTGRES_USER
              value: cast_db_username
            - name: POSTGRES_PASSWORD
              value: cast_db_password
            - name: POSTGRES_DB
              value: cast_db_dev
          ports:
            - name: cast-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP




apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: cast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast
  template:
    metadata:
      labels:
        app: cast
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
            - name: POSTGRES_USER
              value: cast_db_username
            - name: POSTGRES_PASSWORD
              value: cast_db_password
            - name: POSTGRES_DB
              value: cast_db_dev
          ports:
            - name: cast-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP