apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
  labels:
    app: cast
spec:
  selector:
    app: cast
  ports:
  - name: cast-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: LoadBalancer 